### ISSUE TITLE
When will the code be opensourced? 

### ISSUE THREAD

**Issue by TmacTmac1992** [ADLab-AutoDrive/INT#1]
Hi Thanks for your awesome work and when will the code be open sourced

**Comment by HuangVictorAuto** [comment]
@TmacTmac1992 , The code is opensourced, have you implemented it on your own project yet? how is the performance?

**Comment by TmacTmac1992** [comment]
Hi thanks for open-sourced the code. I did used your method in my own project and improve the performance, which is also deploy friendly.  And I find another work use your method and improve the performance:   Exploring Recurrent Long-term Temporal Fusion for Multi-view 3D Perception
